# Generated by Django 2.1 on 2019-03-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('utilizador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredienteName', models.CharField(max_length=100)),
                ('ingredienteQuant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=500)),
                ('preparacao', models.CharField(max_length=3000)),
                ('tempo', models.IntegerField()),
                ('dificuldade', models.CharField(max_length=10)),
                ('dose', models.IntegerField()),
                ('imagem', models.URLField()),
                ('data', models.DateField()),
                ('utilizador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('receitas', models.ManyToManyField(to='app.Receita')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Receita'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Receita'),
        ),
    ]
