# Generated by Django 2.1 on 2019-03-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190318_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tipo',
            field=models.CharField(default='carne', max_length=50),
            preserve_default=False,
        ),
    ]
