# Generated by Django 2.1 on 2019-03-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_receita_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='classificacao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(upload_to='static/portfolio'),
        ),
    ]
