# Generated by Django 2.1 on 2019-03-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ingredientes_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='receitas',
            field=models.ManyToManyField(blank=True, to='app.Receita'),
        ),
    ]
