# Generated by Django 2.1 on 2019-03-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190328_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitasGostadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizador', models.CharField(max_length=100)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Receita')),
            ],
        ),
    ]
